Metnum update 2022
ccfd/courses pull request #92
Opened 2022-03-03 09:28 UTC by kmarchlewski

Small updates:
 - removed outdated announcements (`metnum_ogloszenie.md`) and dates (`metnum_regulamin.md`),
 - added a new function in `metnum_lab1.md` to improve work during exercises.

2022-03-03 09:36 UTC, kubagalecki requested changes

2022-03-03 09:36 UTC, kubagalecki commented on metnum_regulamin.md
> +Przedmiot składa się z 15 h wykładów oraz 7 h spotkań laboratoryjnych (po 1,5 h).
Jest chyba 7 spotkań po 1.5h, czy coś się zmieniło?

2022-03-03 09:47 UTC, kmarchlewski commented on metnum_regulamin.md
> +Przedmiot składa się z 15 h wykładów oraz 7 h spotkań laboratoryjnych (po 1,5 h).
Tak, masz rację. Już poprawiłem.

2022-03-03 09:49 UTC, kubagalecki approved these changes
No i super :) System recenzji zadziałał!

2022-03-03 09:54 UTC, kmarchlewski commented
Tak, recenzje są super. Jak widać na złączonym przykładzie wszędzie da się zrobić błąd.

2022-03-03 09:57 UTC, merged

2022-03-23 08:46 UTC, kmarchlewski commented
Visual Studio 2019 forbids casting from `const char []` to `char *` what results in errors. I will update files winbgi2.h and winbgi2.cpp to address this issue.